global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9000'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'train-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080'] ## only for demo purposes don't use host.docker.internal in production