apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-service
  template:
    metadata:
      labels:
        app: train-service
    spec:
      containers:
        - name: train-service
#          image: registry.digitalocean.com/ticket-katun/tkt-train-service:${TAG}
          image: registry.digitalocean.com/ticket-katun/tkt-train-service:5bb8555
          env:
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: common-config
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                  name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: train-service
spec:
  type: NodePort
  selector:
    app: train-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: train-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://ticket-katun-do-user-15328471-0.d.db.ondigitalocean.com:25060/defaultdb?sslmode=require"