name: Kafka UI Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'k8s/manifests/infrastructure/kafka-ui.yml'  # Adjust if necessary

  workflow_dispatch:
    inputs:
      version:
        description: 'Kafka UI Image Version'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
        
      - name: Deploy to kubernetes
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_ID }}

      - name: Apply Deployment YAML
        run: |
          kubectl apply -f k8s/manifests/infrastructure/kafka-ui.yml

      - name: Kubernetes rollout restart
        run: |
          kubectl -n default rollout restart deployment kafka-ui